//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.24 at 01:30:39 PM IST 
//


package saas.logging.demo.object;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the saas.logging.demo.object package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResponseObject_QNAME = new QName("", "ResponseObject");
    private final static QName _RequestObject_QNAME = new QName("", "RequestObject");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: saas.logging.demo.object
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestObject }
     * 
     */
    public RequestObject createRequestObject() {
        return new RequestObject();
    }

    /**
     * Create an instance of {@link Logs }
     * 
     */
    public Logs createLogs() {
        return new Logs();
    }

    /**
     * Create an instance of {@link ResponseObject }
     * 
     */
    public ResponseObject createResponseObject() {
        return new ResponseObject();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResponseObject")
    public JAXBElement<ResponseObject> createResponseObject(ResponseObject value) {
        return new JAXBElement<ResponseObject>(_ResponseObject_QNAME, ResponseObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RequestObject")
    public JAXBElement<RequestObject> createRequestObject(RequestObject value) {
        return new JAXBElement<RequestObject>(_RequestObject_QNAME, RequestObject.class, null, value);
    }

}
